apiVersion: batch/v1
kind: Job
metadata:
  name: setup-mongodb
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app.kubernetes.io/name: mongodb-configure
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if .Values.job.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongodb-configure
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for-mongodb
          image: python:3.13.1-alpine
          command: ['sh', '-c']
          envFrom:
            - secretRef:
                name: mongo-credentials
          args:
            - |
              echo "Installing pymongo..."
              pip install --no-cache-dir pymongo

              echo "Waiting for MongoDB replica set to be ready..."
              python3 /app/wait.py
          volumeMounts:
            - mountPath: /app/wait.py
              name: script
              subPath: wait.py
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      containers:
        - name: job
          image: python:3.13.1-slim
          command: ["/bin/sh", "-c"]
          args: [
            "pip install --no-cache-dir pyyaml motor && python /app/script.py"
          ]
          envFrom:
            - secretRef:
                name: mongo-credentials
          volumeMounts:
            - mountPath: /app/script.py
              name: script
              subPath: script.py
            - mountPath: /app/config/scopes.yml
              name: script
              subPath: scopes.yml
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      restartPolicy: Never
      volumes:
        - name: script
          configMap:
            name: setup-mongodb
  backoffLimit: 4
